[project]
name = "udacity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "darts>=0.35.0",
    "polygon-api-client>=1.14.6",
    "yfinance>=0.2.61",
]
